# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D://pywork/Board1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from csvTest import *
import matplotlib.pyplot as plt
class Ui_DashBoard(object):
    def setupUi(self, DashBoard):
        DashBoard.setObjectName("DashBoard")
        DashBoard.resize(1280, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DashBoard.sizePolicy().hasHeightForWidth())
        DashBoard.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(DashBoard)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(0, 0, 380, 20))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.labelModa = QtWidgets.QLabel(self.centralwidget)
        self.labelModa.setGeometry(QtCore.QRect(0, 20, 320, 100))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(17)
        self.labelModa.setFont(font)
        self.labelModa.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.labelModa.setObjectName("labelModa")
        self.labelMiddle = QtWidgets.QLabel(self.centralwidget)
        self.labelMiddle.setGeometry(QtCore.QRect(320, 20, 320, 100))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(17)
        self.labelMiddle.setFont(font)
        self.labelMiddle.setStyleSheet("background-color: rgb(80, 240, 240);")
        self.labelMiddle.setObjectName("labelMiddle")
        self.labelMax = QtWidgets.QLabel(self.centralwidget)
        self.labelMax.setGeometry(QtCore.QRect(0, 120, 320, 100))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(17)
        self.labelMax.setFont(font)
        self.labelMax.setStyleSheet("background-color: rgb(0, 226, 226);")
        self.labelMax.setObjectName("labelMax")
        self.labelGraphics = QtWidgets.QLabel(self.centralwidget)
        self.labelGraphics.setGeometry(QtCore.QRect(0, 220, 640, 480))
        self.labelGraphics.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.labelGraphics.setText("")
        self.labelGraphics.setObjectName("labelGraphics")
        self.labelLISTsubject = QtWidgets.QLabel(self.centralwidget)
        self.labelLISTsubject.setGeometry(QtCore.QRect(640, 70, 640, 630))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelLISTsubject.setFont(font)
        self.labelLISTsubject.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.labelLISTsubject.setObjectName("labelLISTsubject")
        self.labelAVGsubject = QtWidgets.QLabel(self.centralwidget)
        self.labelAVGsubject.setGeometry(QtCore.QRect(640, 20, 640, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelAVGsubject.setFont(font)
        self.labelAVGsubject.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelAVGsubject.setObjectName("labelAVGsubject")
        self.labelMin = QtWidgets.QLabel(self.centralwidget)
        self.labelMin.setGeometry(QtCore.QRect(320, 120, 320, 100))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(17)
        self.labelMin.setFont(font)
        self.labelMin.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.labelMin.setObjectName("labelMin")
        self.Filler = QtWidgets.QLabel(self.centralwidget)
        self.Filler.setGeometry(QtCore.QRect(0, 700, 1280, 31))
        self.Filler.setStyleSheet("background-color: rgb(0, 136, 136);")
        self.Filler.setText("")
        self.Filler.setObjectName("Filler")
        DashBoard.setCentralWidget(self.centralwidget)

        self.retranslateUi(DashBoard)
        QtCore.QMetaObject.connectSlotsByName(DashBoard)

        self.EditInfo()

    def retranslateUi(self, DashBoard):
        _translate = QtCore.QCoreApplication.translate
        DashBoard.setWindowTitle(_translate("DashBoard", "MainWindow"))
        self.comboBox.setItemText(0, _translate("DashBoard", "Выбрать предмет"))
        self.comboBox.setItemText(1, _translate("DashBoard", "Все предметы"))
        self.comboBox.setItemText(2, _translate("DashBoard", "Математика"))
        self.comboBox.setItemText(3, _translate("DashBoard", "Инфокоммуникационные системы и сети"))
        self.comboBox.setItemText(4, _translate("DashBoard", "Социология"))
        self.comboBox.setItemText(5, _translate("DashBoard", "Инженерная геометрия и компьютерная графика"))
        self.comboBox.setItemText(6, _translate("DashBoard", "Языки программирования и методы трансляции"))
        self.labelModa.setText(_translate("DashBoard", "МОДА"))
        self.labelMiddle.setText(_translate("DashBoard", "МЕДИАНА"))
        self.labelMax.setText(_translate("DashBoard", "МАКСИМУМ ОЦЕНКА"))
        self.labelLISTsubject.setText(_translate("DashBoard", "ФИО студента и оценка по предмету"))
        self.labelAVGsubject.setText(_translate("DashBoard", "Среднее арифмитическое по предмету"))
        self.labelMin.setText(_translate("DashBoard", "МИНИМУМ ОЦЕНКА"))

    def EditInfo(self):
        self.comboBox.textActivated.connect(self.comboBox_switch)

    def comboBox_switch(self,text):
        self.labelAVGsubject.setText(text)
        if self.labelAVGsubject.text() == "Выбрать предмет":
            self.labelMin.setText("МИНИМУМ ОЦЕНКА")
            self.labelMax.setText("МАКСИМУМ ОЦЕНКА")
            self.labelModa.setText("МОДА")
            self.labelMiddle.setText("МЕДИАНА")
            self.labelAVGsubject.setText("Среднее арифмитическое по предмету")
            self.labelLISTsubject.setText("ФИО студента и оценка по предмету")
            self.labelGraphics.setPixmap(QtGui.QPixmap("D://pywork/background.png"))
        if self.labelAVGsubject.text() == "Все предметы":
            self.labelMin.setText("Отметка с наименьшим \nзначением: "+retranslate(Min(0)[1]))
            self.labelMax.setText("Отметка с наибольшим \nзначением: "+retranslate(Max(0)[1]))
            self.labelModa.setText("Наиболее частая \nотметка: "+retranslate(Moda(0)[1]))
            self.labelMiddle.setText("Средняя отметка в \nчисловом значении: "+str(Middle(0)[1]))
            self.labelAVGsubject.setText("Среднее арифмитическое по всем предметам у всех студентов: "+str(ArithmeticMeanEntire(ArithmeticMean(0,students))))
            self.labelLISTsubject.setText(SortingListEntire(ArithmeticMean(0,students)))
            self.plot_graphics(0)
            self.labelGraphics.setPixmap(QtGui.QPixmap("D://pywork/graphics.png"))
        if self.labelAVGsubject.text() == "Математика":
            self.EditLabels(1)
        if self.labelAVGsubject.text() == "Инфокоммуникационные системы и сети":
            self.EditLabels(2)
        if self.labelAVGsubject.text() == "Социология":
            self.EditLabels(3)
        if self.labelAVGsubject.text() == "Инженерная геометрия и компьютерная графика":
            self.EditLabels(4)
        if self.labelAVGsubject.text() == "Языки программирования и методы трансляции":
            self.EditLabels(5)

    def EditLabels(self,numberSubject):
        self.labelMin.setText("Отметка с наименьшим \nзначением: " + retranslate(Min(numberSubject)[1]))
        self.labelMax.setText("Отметка с наибольшим \nзначением: " + retranslate(Max(numberSubject)[1]))
        self.labelModa.setText("Наиболее частая \nотметка: " + retranslate(Moda(numberSubject)[1]))
        self.labelMiddle.setText("Средняя отметка в \nчисловом значении: " + str(Middle(numberSubject)[1]))
        Subject=""
        if numberSubject==1:
            Subject = "Матем."
        if numberSubject==2:
            Subject = "ИСиС"
        if numberSubject==3:
            Subject = "Социол."
        if numberSubject==4:
            Subject = "ИГиКГ"
        if numberSubject==5:
            Subject = "ЯПиМТ"
        self.labelAVGsubject.setText("Среднее арифмитическое по предмету "+Subject+" у всех студентов: " + str(
            ArithmeticMean(numberSubject)[1]))
        self.labelLISTsubject.setText(SortingListSubject(numberSubject))
        self.plot_graphics(numberSubject)
        self.labelGraphics.setPixmap(QtGui.QPixmap("D://pywork/graphics.png"))
    def plot_graphics(self,number):
        grades = []
        if number == 0:
            for counter in range(1, len(DisciplineGrades(0))):
                grades.append(DisciplineGrades(0, students)[counter][1])
        elif number > 0 and number < len(disciplines):
            for counter in range(1,len(DisciplineGrades(number))):
                grades.append(DisciplineGrades(number,students)[counter][1])
        plt.plot(grades)
        plt.savefig('graphics.png')
        plt.clf()
